# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='princable',
            new_name='principal',
        ),
    ]
