# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190611_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
